### PR TITLE
Pluggable config server feature RFC#0019

### PR DESCRIPTION
**Pull request by santoshaherkar**
RFC#0019: networknt/light-rfcs#28

### CODE REVIEW

**Comment by zabooma** [comment]
Moved base to master

**Comment by santoshaherkar** [comment]
I see the Travis CI build is failed on client module here but on my local, it runs all fine:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:24 min
[INFO] Finished at: 2019-04-04T17:03:06-04:00
[INFO] Final Memory: 42M/561M
[INFO] ------------------------------------------------------------------------

**Comment by stevehu** [comment]
It's been a while that we have supported the values.yml file for centralized config value management. I am thinking to update the config server to serve a JSON with all the values instead of downloading a zip of config files. What do you think? Should we still keep the current zip file based config server and add another endpoint to server values or just eliminate the zip file implementation?

**Comment by zabooma** [comment]
That is the idea that we are exploring now. The changes that Santosh is making are positioning framework to support different config servers and corresponding client side loaders.

⁣Regards, 
Frank Povazanj

**Comment by santoshaherkar** [comment]
@stevehu that's exactly what we are doing in our config server implementation. But I have not touched the existing implementation; I just moved the code as it is into DefaultConfigLoader class.

**Comment by stevehu** [comment]
I am so glad that we are on the same page. Thanks.

**Comment by NicholasAzar** [comment]
@santoshaherkar can you resolve the conflicts in this?

**Comment by NicholasAzar** [comment]
@santoshaherkar thanks! also can you revert the changes to the license header in those few files?

**Comment by santoshaherkar** [comment]
@NicholasAzar I have resolved the conflict & reverted license header changes as well. 
Can we get this PR reviewed/approved/merged as soon as possible to avoid any more conflicts? I have resolved them 4th time now :)

**Comment by stevehu** [comment]
@NicholasAzar I think it is backward compatible now and startup.yml is only required if a customized implementation is used.

**Comment by stevehu** [comment]
[Pluggable config server feature RFC#0019](https://trello.com/c/2el4z6b9/169-pluggable-config-server-feature-rfc0019)

**Pull request merged**
