### PR TITLE
Make SSL private to prevent its usage before it is initialized. 

### PR DESCRIPTION
**Pull request by miklish**
See issue #629 for full details.

### CODE REVIEW

**Comment by miklish** [comment]
Found another usage of SSL in light-4j (OAuthHelper)… WIll fix and update PR branch

**Comment by miklish** [comment]
Sorry folks... as mentioned, there are more cases where the variable SSL is used directly that weren't updated... updating now

**Comment by stevehu** [comment]
I think this breaks a lot of existing applications. If we don't do anything, all existing applications should work.

**Comment by miklish** [comment]
I fixed it so it builds now, but the Audit Handler unit tests are failing. I'm examining why this is.  As for breaking existing applications, that is a good thing. The alternative is apps that build but fail when run.

**Comment by miklish** [comment]
I figured out why some of the unit tests were failing. They use Http2Client.SSL in the test, but do not have any truststores configured. The solution is simply to delete the Http2Client.SSL argument.

The problem was that I had replaced the Http2Client.SSL argument with Http2Client.getInstance().getDefaultXnioSSL() which caused the client to look for truststores that were not configured.

**Comment by miklish** [comment]
Ok, as per our discussion, this change should be reverted, as it causes to many issues in other related repos. We will instead deprecate Http2Client.SSL

**Pull request merged**
