### PR TITLE
514 sanitizer new config properties

### PR DESCRIPTION
**Pull request by jefperito**
#514 
attributesToAppreciate: attributes for apply encoding (ignore everything else)
attributesToIgnore: attributes for ignore encoding (apply everything else)

### CODE REVIEW

**Comment by stevehu** [comment]
@jefperito I have manually synced the master to the feature branch as the base has been changed from jdk8 to jdk11. One question: why do you name the positive list as attributesToAppreciate instead of attributesToEncode?

**Comment by jefperito** [comment]
Sure, it's seems a better name to this purpose

**Comment by jefperito** [comment]
done, that commit adds an integration test for encoding extended by client.

**Comment by jefperito** [comment]
i don't know why that build step is broken:

"No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."

**Comment by stevehu** [comment]
It seems we have some problem with Travis. The local build is OK always and I guess the multiple threads test in client module is not working on Travis as it only allocates one thread per build. There might be other reasons but I don't know. It is nothing to do with this PR.

**Pull request merged**
