### PR TITLE
move classes in undertow package to networknet packages - #433

### PR DESCRIPTION
**Pull request by dz-1**

### CODE REVIEW

**Comment by stevehu** [comment]
The Undertow code is using JBoss logger and I don't know if it checks the logging level before evaluating the expressions. I think we should switch logging to slf4j so that it can be controlled by our logback.xml on production. What do you think?

**Comment by dz-1** [comment]
ok. let me fix the test failure first.

**Comment by ddobrin** [comment]
I think that it's only natural to move to slf4j, agreed

**Comment by dz-1** [comment]
The undertow package `io.undertow.client.http` pulls in a lot of dependencies and some classes are generated from annotations. It's very difficult, and also risky, to copy the code and make them work properly.
So, I changed the implementation to use java reflection to create instances of `io.undertow.client.http. HttpClientConnection`. This is a little bit hacky but is safer than copying the code.

**Comment by NicholasAzar** [comment]
@stevehu did this break the build?

**Comment by stevehu** [comment]
I have fixed it and merged it. It was detected by the light-bot.

**Comment by NicholasAzar** [comment]
Doesn't this repo have a check before it can be merged to prevent that? I would have thought it would be detected here

**Comment by dz-1** [comment]
The build passed and I checked locally. That build error may be introduced during merge.

**Comment by stevehu** [comment]
I think it checks with Travis; however, I found it is not reliable with feature branches. I am running the light-bot after merging so anything can be captured very fast.

**Comment by NicholasAzar** [comment]
[move classes in undertow package to networknet packages](https://trello.com/c/vdyQleHm/126-move-classes-in-undertow-package-to-networknet-packages)

**Comment by NicholasAzar** [comment]
[move classes in undertow package to networknet packages](https://trello.com/c/vdyQleHm/126-move-classes-in-undertow-package-to-networknet-packages)

**Pull request merged**
