### PR TITLE
Adding HandlerProvider support to list of handlers.

### PR DESCRIPTION
**Pull request by NicholasAzar**
#258

### CODE REVIEW

**Comment by NicholasAzar** [comment]
@logi fyi

**Comment by ddobrin** [comment]
Hi @NicholasAzar,
Is there an example on how HandlerProviders would be added to the handler.yml?

**Comment by NicholasAzar** [comment]
@ddobrin it would be the same way as HttpHandlers without constructors. Nothing new in the `handler.yml` interface definition as part of this change.

**Comment by ddobrin** [comment]
@NicholasAzar : I agree that we should fail fast here, as we wish to support only certain type of handlers (if need be, it can be enhanced on demand later)

**Pull request merged**
