### PR TITLE
Fix/#590 skip tests

### PR DESCRIPTION
**Pull request by BalloonWen**
-related issue: https://github.com/networknt/light-4j/issues/590
to make the existing user keep using "DskipTests", change the "skip.unit.tests" to property "skipTests"
when run integration test, using "-P integration-test"
-added some integration test files to fix some integration tests, the configs of integration tests and unit tests are independent after the change of issue https://github.com/networknt/light-4j/issues/502

### CODE REVIEW

**Comment by BalloonWen** [comment]
> I tried to build with `mvn clean install -Pintegration-test` and it failed at the server module. After adding client.truststore and client.keystore, there were still some issues with the integration tests.

yes, and I believe there was some integration tests failure before due to the different configs. This PR is not major for fixing the IT build, but to make the -DkipTests works.
Those failure tests are from ConsulRegistryIT, which implemented by @jiachen1120 , there are some complex logic in it, I may need his help and fix this in another issue.

**Comment by stevehu** [comment]
@BalloonWen I agree. This is not the issue introduced by this PR. I will create another issue to address the integration test. Thanks.

**Comment by stevehu** [comment]
https://github.com/networknt/light-4j/issues/594

**Comment by jiachen1120** [comment]
@stevehu Hi! I just fixed the consul integration test by change the test case from checking the `exception` to checking `null`. 

We changed the behaviour of  `serviceToUrl()` method in 1.6.5. Currently, this method will return `null` instead of throw NPE when service cannot be found.  But we didn't change the corresponding test case inside the consul integration test. After this slight change the test should work now.

**Comment by stevehu** [comment]
@jiachen1120 This makes perfect sense. Thanks a lot for the fix.

**Comment by stevehu** [comment]
@jiachen1120 I tried to run the integration test with the latest code in this branch and found this error. It appears that the container is not started correctly on my local. I just run the command `mvn clean install -Pintegration-test`. Am I missing something? 

```
Failed to register service, the server stopped.
com.networknt.exception.FrameworkException: {"statusCode":500,"code":"ERR10020","message":"REGISTER_ERROR","description":"Class ConsulRegistry fails to register light://127.0.0.1:49589/com.networknt.petstore-1.0.0?group=default to http://localhost:32800/?group=default","severity":"ERROR"}
	at com.networknt.registry.support.FailbackRegistry.register(FailbackRegistry.java:86)
	at com.networknt.server.Server.register(Server.java:497)
	at com.networknt.server.Server.bind(Server.java:289)
	at com.networknt.server.Server.start(Server.java:193)
	at com.networknt.server.ConsulRegistryIT.lambda$startServer$0(ConsulRegistryIT.java:199)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: Command consul registry not support available by urls yet
	at com.networknt.consul.ConsulRegistry.doAvailable(ConsulRegistry.java:93)
	at com.networknt.registry.support.AbstractRegistry.available(AbstractRegistry.java:164)
	at com.networknt.registry.support.FailbackRegistry.available(FailbackRegistry.java:45)
	at com.networknt.registry.support.AbstractRegistry.register(AbstractRegistry.java:81)
	at com.networknt.registry.support.FailbackRegistry.register(FailbackRegistry.java:83)
	... 5 more
21:29:01.258 [Thread-15]       INFO  com.networknt.server.Server - Failed to register service, the server stopped.
com.networknt.exception.FrameworkException: {"statusCode":500,"code":"ERR10020","message":"REGISTER_ERROR","description":"Class ConsulRegistry fails to register light://127.0.0.1:49589/com.networknt.petstore-1.0.0?group=default to http://localhost:32800/?group=default","severity":"ERROR"}
	at com.networknt.registry.support.FailbackRegistry.register(FailbackRegistry.java:86)
	at com.networknt.server.Server.register(Server.java:497)
	at com.networknt.server.Server.bind(Server.java:289)
	at com.networknt.server.Server.start(Server.java:193)
	at com.networknt.server.ConsulRegistryIT.lambda$startServer$0(ConsulRegistryIT.java:199)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: Command consul registry not support available by urls yet
	at com.networknt.consul.ConsulRegistry.doAvailable(ConsulRegistry.java:93)
	at com.networknt.registry.support.AbstractRegistry.available(AbstractRegistry.java:164)
	at com.networknt.registry.support.FailbackRegistry.available(FailbackRegistry.java:45)
	at com.networknt.registry.support.AbstractRegistry.register(AbstractRegistry.java:81)
	at com.networknt.registry.support.FailbackRegistry.register(FailbackRegistry.java:83)
	... 5 common frames omitted
Exception in thread "Thread-15" java.lang.RuntimeException: {"statusCode":500,"code":"ERR10020","message":"REGISTER_ERROR","description":"Class ConsulRegistry fails to register light://127.0.0.1:49589/com.networknt.petstore-1.0.0?group=default to http://localhost:32800/?group=default","severity":"ERROR"}
	at com.networknt.server.Server.register(Server.java:505)
	at com.networknt.server.Server.bind(Server.java:289)
	at com.networknt.server.Server.start(Server.java:193)
	at com.networknt.server.ConsulRegistryIT.lambda$startServer$0(ConsulRegistryIT.java:199)
	at java.lang.Thread.run(Thread.java:748)
21:29:06.116 [main]       INFO  c.networknt.server.ConsulRegistryIT - starting server

```

**Comment by jiachen1120** [comment]
@stevehu Hi! After debugging into it. 
I found this problem because I started three services in one test. When the first service is successfully registered. `REGISTRY_HEARTBEAT_SWITCHER` will be set to `On`. When this switch is on, other services will not pass the `doAvailable` method after completing the registration, and the final error message will be register fail instead of available fail. I think this exception message maybe should be change to be more accurate.
The following code block shows the switcher check
```java
if (SwitcherUtil.isOpen(Constants.REGISTRY_HEARTBEAT_SWITCHER)) {
            available(url);
        }
```
After setting it manually to false, the test can pass. However, I don’t fully understand how this part works. The doAvailable method seems cannot pass if the url exist.
```java
protected void doAvailable(URL url) {
        if (url == null) {
            if(getConsulConfig().ttlCheck) heartbeatManager.setHeartbeatOpen(true);
        } else {
            throw new UnsupportedOperationException("Command consul registry not support available by urls yet");
        }
    }
```

**Comment by stevehu** [comment]
@jiachen1120 The switcher is to prevent the service get accessed during the startup at the stage the TCP/IP socket is open but the service initialization is not done yet. The switch explicitly indicates that the service is ready to serve the clients. 

I have tested the latest code on my local and go the following error instead. 

```
16:34:41.184 [Thread-18]       INFO  c.n.r.support.AbstractRegistry - [ConsulRegistry] Url (light://127.0.0.1:49590/com.networknt.petstore-1.0.0?group=default) will unregister to Registry [http://localhost:32818/default//1.0/service]
16:34:41.184 [Thread-14]       INFO  c.n.r.support.AbstractRegistry - [ConsulRegistry] Url (light://127.0.0.1:49590/com.networknt.petstore-1.0.0?group=default) will unregister to Registry [http://localhost:32818/default//1.0/service]
16:34:41.186 [Thread-16]       INFO  c.n.r.support.AbstractRegistry - [ConsulRegistry] Url (light://127.0.0.1:49590/com.networknt.petstore-1.0.0?group=default) will unregister to Registry [http://localhost:32818/default//1.0/service]
16:34:41.187 [Thread-18]       ERROR c.n.consul.client.ConsulClientImpl - cannot create connection to consul http://localhost:32818 due to: Connection refused
16:34:41.187 [Thread-16]       ERROR c.n.consul.client.ConsulClientImpl - cannot create connection to consul http://localhost:32818 due to: Connection refused
16:34:41.187 [Thread-14]       ERROR c.n.consul.client.ConsulClientImpl - cannot create connection to consul http://localhost:32818 due to: Connection refused
16:34:41.190 [Thread-16]       ERROR c.n.consul.client.ConsulClientImpl - Failed to unregister on Consul, Exception:
java.lang.NullPointerException: null
	at com.networknt.consul.client.ConsulClientImpl$ConsulConnection.send(ConsulClientImpl.java:301)
	at com.networknt.consul.client.ConsulClientImpl.unregisterService(ConsulClientImpl.java:157)
	at com.networknt.consul.ConsulRegistry.doUnregister(ConsulRegistry.java:84)
	at com.networknt.registry.support.AbstractRegistry.unregister(AbstractRegistry.java:93)
	at com.networknt.registry.support.FailbackRegistry.unregister(FailbackRegistry.java:98)
	at com.networknt.server.Server.shutdown(Server.java:334)
	at com.networknt.server.Server$1.run(Server.java:366)
16:34:41.190 [Thread-18]       ERROR c.n.consul.client.ConsulClientImpl - Failed to unregister on Consul, Exception:
java.lang.NullPointerException: null
	at com.networknt.consul.client.ConsulClientImpl$ConsulConnection.send(ConsulClientImpl.java:301)
	at com.networknt.consul.client.ConsulClientImpl.unregisterService(ConsulClientImpl.java:157)
	at com.networknt.consul.ConsulRegistry.doUnregister(ConsulRegistry.java:84)
	at com.networknt.registry.support.AbstractRegistry.unregister(AbstractRegistry.java:93)
	at com.networknt.registry.support.FailbackRegistry.unregister(FailbackRegistry.java:98)
	at com.networknt.server.Server.shutdown(Server.java:334)
	at com.networknt.server.Server$1.run(Server.java:366)
unregister serviceUrl light://127.0.0.1:49590/com.networknt.petstore-1.0.0?group=default
16:34:41.190 [Thread-14]       ERROR c.n.consul.client.ConsulClientImpl - Failed to unregister on Consul, Exception:
java.lang.NullPointerException: null
	at com.networknt.consul.client.ConsulClientImpl$ConsulConnection.send(ConsulClientImpl.java:301)
	at com.networknt.consul.client.ConsulClientImpl.unregisterService(ConsulClientImpl.java:157)
	at com.networknt.consul.ConsulRegistry.doUnregister(ConsulRegistry.java:84)
	at com.networknt.registry.support.AbstractRegistry.unregister(AbstractRegistry.java:93)
	at com.networknt.registry.support.FailbackRegistry.unregister(FailbackRegistry.java:98)
	at com.networknt.server.Server.shutdown(Server.java:334)
	at com.networknt.server.Server$1.run(Server.java:366)
unregister serviceUrl light://127.0.0.1:49590/com.networknt.petstore-1.0.0?group=default
16:34:41.190 [Thread-16]       INFO  com.networknt.server.Server - unregister serviceUrl light://127.0.0.1:49590/com.networknt.petstore-1.0.0?group=default
unregister serviceUrl light://127.0.0.1:49590/com.networknt.petstore-1.0.0?group=default
16:34:41.190 [Thread-16]       INFO  com.networknt.server.Server - Starting graceful shutdown.

```

**Comment by jiachen1120** [comment]
@stevehu Hello! After investigation, the reason for this error is that test container will be shut down before the @Afterclass annotation is executed, so the unregistering process in the @afterclass can't find the consul running in the container. This bug can be fixed by skipping unregistering in @afterclass. It would not influent what we want to test with consul.

**Comment by stevehu** [comment]
It might be a timing issue on my local. I tried with the latest code and still got failed test cases. It looks like the lookup are all returned empty result. 

```
Https Server started on ip:0.0.0.0 Port:49590
16:46:36.331 [Thread-231]       INFO  com.networknt.server.Server - Https Server started on ip:0.0.0.0 Port:49590
16:46:47.253 [main]       INFO  c.n.r.support.AbstractRegistry - [ConsulRegistry] Listener (com.networknt.cluster.LightCluster$ClusterNotifyListener@57d8d8e2) will subscribe to url (https://localhost:443/com.networknt.petstore-1.0.0?group=default) in Registry [http://localhost:32782/default//1.0/service]
16:46:47.254 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry subscribe. url: https://localhost:443/com.networknt.petstore-1.0.0?group=default
16:46:47.256 [main]       INFO  c.n.r.s.c.CommandServiceManager - CommandServiceManager init url:https://localhost:443/com.networknt.petstore-1.0.0?environment=dev&
16:46:47.258 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover. url: https://localhost:443/com.networknt.petstore-1.0.0?group=default
16:46:47.258 [Thread-233]       INFO  com.networknt.consul.ConsulRegistry - start service lookup thread. lookup interval: 30000ms, service: com.networknt.petstore-1.0.0
16:46:47.274 [main]       INFO  com.networknt.consul.ConsulRegistry - no response for service: com.networknt.petstore-1.0.0, set urls to null
16:46:47.277 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover size: 0, result:[]
16:46:47.277 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover. url: https://localhost:443/com.networknt.petstore-1.0.0?group=default
16:46:47.278 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover size: 0, result:[]
16:46:49.278 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover. url: https://localhost:443/com.networknt.petstore-1.0.0?group=default
16:46:49.279 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover size: 0, result:[]
16:46:51.280 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover. url: https://localhost:443/com.networknt.petstore-1.0.0?group=default
16:46:51.281 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover size: 0, result:[]
16:46:53.281 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover. url: https://localhost:443/com.networknt.petstore-1.0.0?group=default
16:46:53.282 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover size: 0, result:[]
16:46:55.283 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover. url: https://localhost:443/com.networknt.petstore-1.0.0?group=default
16:46:55.283 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - CommandFailbackRegistry discover size: 0, result:[]
16:46:57.287 [main]       INFO  c.n.r.support.AbstractRegistry - [ConsulRegistry] Listener (com.networknt.cluster.LightCluster$ClusterNotifyListener@2a4bee4e) will subscribe to url (https://localhost:443/com.networknt.petstore-1.0.0?group=default) in Registry [http://localhost:32782/default//1.0/service]
16:46:57.287 [main]       INFO  c.n.r.s.c.CommandFailbackRegistry - Com
```

**Comment by jiachen1120** [comment]
@stevehu Hi! I think it should be. It is hard to determine how long the service registration will complete with a container consul. Therefore, the time I picked maybe only apply to my computer. Even though we provide a long delay for the service registration, it still cannot make sure everyone can pass the test in their computer. And the integration test will be very slow. 

Could you please provide some idea about this? or we skip this test and let those people who have concern with consul to use it manually before generate a good solution instead of stacking on this integration test?

**Comment by stevehu** [comment]
@jiachen1120 I agree with you about the timing issue. I think we can leave this test case there as most people will never run the -Pintegration-test but only our developers. If it works on your computer, it is valuable. Could you please review and approve the rest of the PR? Thanks.

**Pull request merged**
