### PR TITLE
Feat/connection pool

### PR DESCRIPTION
**Pull request by jiachen1120**
Related issue: https://github.com/networknt/light-4j/issues/572 https://github.com/networknt/light-4j/issues/595

This PR implements the connection pool of http2client to optimize the connection establishment of the http2client module.

**implementation**

By embedding the connection pool into an existing method
```java
CompletableFuture<ClientResponse> callService(URI uri, ClientRequest request, Optional<String> requestBody)
```
, the user can call this method or `getRequestService(URI uri, ClientRequest request, Optional<String> requestBody)` which combine the `callService()` with circuit breaker to cache the established connections and reuse them without considering the type of connection.

When the connection is http/1.1, multiple connections will be added to the connection pool for the same host. The workflow is to monitor whether there are connections that are not yet occupied by other requests and are not waiting for a response when a request is sent. If so, reuse the connection until the connection is closed or the maximum number of requests is reached, otherwise a new connection is established and cached into connection pool for this host.

When the connection is http/2, only one connection will be added to the connection pool for the same host. When sending a request, reuse it until the connection is closed or the maximum number of requests is reached. When the connection is not encrypted(using the http protocol), more than one connection will be added to the connection pool. This is because the undertow will first establish a http/1.1 connection and then upgrade it to http2 instead of directly establishing http/2 connections.

The connection pool uses the LRU mechanism. Least recently used connection will be removed when the connection pool size reaches the set value. 

**Configuration** 

Users can configure the size of the connection pool; the maximum number of requests per connection and whether http/2 is enabled by configuring client.yml.

Or, user can clean up the connection pool manually by calling `Http2ClientConnnectionPool.getInstance().clear()`

For example,
```yml
request:
  errorThreshold: 2
  timeout: 3000
  resetTimeout: 7000
  enableHttp2: false
  connectionPoolSize: 1000
  maxReqPerConn: 1000000
```

**Example**

```java
try {
    ClientRequest requestB = new ClientRequest().setMethod(Methods.GET).setPath(apibPath);
    
    CompletableFuture<ClientResponse> response = client.callService(new URI(apibHost), requestB, Optional.empty());
    
    int statusCodeB = response.join().getResponseCode();
    if (statusCodeB >= 300) {
        throw new Exception("Failed to call API B: " + statusCodeB);
    }
    String apibList = response.join().getAttachment(Http2Client.RESPONSE_BODY);
} catch (Exception e) {
    logger.error("Exception:", e);
    throw new ClientException(e);
}
```

### CODE REVIEW

**Comment by stevehu** [comment]
@jiachen1120 This is so cool and it is a long-waited feature for a lot of users. Thanks a lot for putting it all together. I haven't read the code yet and I might be wrong. Regarding the HTTP/1.1 connection reuse, my understanding is that one connection can only be reused in the same thread as it would be too hard to sync different thread than picking another connection from the pool. I need to understand the implementation first but something comes up when I read your document above and I don't want to forget about it.

**Comment by jiachen1120** [comment]
@stevehu Hi! Thanks for quick response! 

In order to deal with the above situation. I created a state map to record the usage of each connection. For http/1.1, there are three states: `hanging`, `available`, `close`. Whenever a request is sent, a connection with the status `available` will be randomly picked from the connection pool, and immediately change its state to `hanging` to prevent other thread gets the connection. This method is synchronized, so that at http/1.1, different threads would not get the same connection with the available status.

When a connection response returns, the method responsible for resetting the status is called, and the status of connection is reset to `avaliable` if the connection is not closed or the maximum number of requests is reached.

After testing, it seems work properly. I will further considering about it.

**Comment by stevehu** [comment]
The logic sounds very good. For HTTP/1.1 connection, do we need to limit the number of the request per connection? I think the number of multiplex requests is the limitation for HTTP/2 only. Thanks.

**Comment by jiachen1120** [comment]
@stevehu 
Yes, I think you are right. I can remove this check for http/1.1 if there is no problem with unlimited reuse of http/1.1.

I have not tested whether there are any restrictions on the reuse of http / 1.1. Because it is not easy to test, I also did not find the ideal answer on google. So I chose a more insurance method, which is a unified restriction with http 2. 😂

**Comment by stevehu** [comment]
Yes. There is no negative impact to set a limit just like the HTTP/2. The limit was introduced in HTTP/2 as the designer using a long number to track the frames. It is considered a bug by a lot of people and will be removed in the future of the protocol.

**Comment by ddobrin** [comment]
@jiachen, @stevehu, 
please allow me to make some notes on this PR.

**1. Reset by request count or time**
For HTTP2, we discover the host using the cluster class:
// discover the host
host = cluster.serviceToUrl("https", serviceID, TAG, null);

we use this host to connect() or to pass into this new method callService():
connection = client.connect(new URI(host), Http2Client.WORKER, Http2Client.SSL, Http2Client.BUFFER_POOL,OptionMap.create(UndertowOptions.ENABLE_HTTP2, useHttp2)).get();

or 
client.callService(new URI(host), request, ....)

The callService() will get a connection from the pool and, if it reaches one of the 2 limits, resets the connection, but within the same URI ! This solves only partially the reset problem, but doesn't balance across multiple hosts, if discovered . from Consul for example.

**we have 2 choices:**
a.  add another class to discover/re-discover, keep count, and set a new config values. We could also leave that to API Teams to build
b. the functionality still has to be built, however we expose the reqcount or time limit as getters in the HTTPClient, if we wish to reuse the same values.

I must implement the first one for my client and it can be shared if found useful.

**2. When a callService call is made** by a microservice, and a different host is passed, and it is HTTP2, the new connection is being added to the pool, however the previously used one is **not evicted from the pool** 

**3. HTTP1.1 - where we have multiple connections in the pool.**

If we set only the maximum size, and the pool is used up (say limit=10), while the microservice is under load, we create a new connection past the limit, however we return it to the pool and evict the oldest.
If the service stays under load, we will in fact create a new connection for every call, which defeats the purpose of the pool.

Can we consider a min and max (HTTP1.1), where we let the pool grow under load (assume a maximum acceptable max size), however let it shrink when not under load.

For example, if the load capacity is dropping at 60-70%, shrink the pool.

**4. The reset count/reset by time needs to be added for HTTP1.1 as well**, as we'd like consumers to reestablish those connections as well.
Please read this comment in line with [1], as we could leave the "rebalancing" up to API developers or not

I think the ideas are all good, maybe we can fine tune/add a bit to address [1-4] above

**Comment by stevehu** [comment]
@ddobrin Thanks a lot for the long comment. I agree that we need to re-balance the backend cluster for each connection reset. I missed this important feature and mistakenly asked @jiachen1120 to remove the reset for HTTP/1.1 connection. 

For point 1, I think we should implement it in the client module instead of asking our users to take responsibility unless there is no easy way to do so.

For point 2, we are using the uri as the key to look up the connection in the pool. So for the same uri, there is only one connection in the pool. I don't think we should remove other connection when a new uri is introduced. Chances are the old uri will be used by another call and the existing connection will be retrieved to complete the request. Is there any reason that we need to evict an HTTP/2 connection?

For point 3, I think the maximum/minimum pool size is a good idea if it is not too hard to implement. This gives users a lot of flexibility and makes the connection pool more adaptive to burst of loads. I think most JDBC connection pool is doing the same. 

For point 4, it is something I missed. The connection reset is not just to fix the HTTP/2 bug but to re-balance the backend service instances as we are using client-side discovery. @jiachen1120 I am sorry to ask you to remove the reset logic.

**Comment by ddobrin** [comment]
[1]
I agree with you @stevehu about the best solution is implementing it in the client, this is what was discussed in the past. 
I am planning for the case that it can't be added easily, then it's a feature which clients will have to handle, and I am OK with that. 

We can do that if we add an additional method (better said, a separate one), or modify this one, where you can pass it serviceID and Tag, then deal with the call within that method.

I am OK with the current control I have with clustering, connection and invocation in a utility class, as I have different security models for my APIs.

An additional class/method should allow consumers to have that flexibility.

And, let's not forget, different  users have different requirements, while several APIs are already deployed in the Cloud and change is not instantaneous.

[2] that connection might be stale, and we want the calls to balance to the next URI; that's the rationale

[3] The min and max is required, I would say, for the following reason:
right now, say max is set to 10, but request #11 arrives. 
pool is max'ed out
a new connection is created
pool stays at size 10
the new connection is added to the pool and the oldest evicted.

If the pool is set to low, or the influx of requests is high, each new requests results in creating a new connection. 

This is why I am suggesting it.

My most important concern is [1]. I can help out if needed

**Comment by stevehu** [comment]
@ddobrin Thanks for the detailed explanation which brings us on the same page. For point 2, it raises another question about the design of our connection pool. What is the key to the connection pool? serviceId or URI? If we use serviceId, it is before the service discovery and we can keep all the connections to each backend service per serviceId. If the key is URI, then the new connection should only be created when a connection is reset or re-balanced. At that time, we don't know how to remove the previous connection. The best place to remove the previous connection is when the limit is reached I think. This is pretty complicated and I can set up a zoom meeting if you guys want to have a group discussion.

**Comment by ddobrin** [comment]
We can discuss it over Zoom, if you guys wish, however my time is limited to tomorrow morning

**Comment by jiachen1120** [comment]
@ddobrin @stevehu 
Thanks for the reviews and suggestions!

[1] [4] Rebalancing is a good point, sorry I ignored this in my previous design. I will find a way to integrate this method in the client. I will delve further into whether introduce a new method or make changes on existing methods.
[2][3] Currently, The connection pool I design can be showed as the following chart:
```
| uris           | connections   list                                |
|----------------|---------------------------------------------------|
| localhost:8080 | Http2ClientConnection                             |
| localhost:8081 | HttpClientConnection1, HttpClientConnection2, ... |
| ...            |                                                   |
```
The key is URI, each uri will corresponding to one or multiple connections depend on the connection type(http/2 or http/1.1)
Oldest entry(URI->connections) instead of oldest connection will be evicted from the connection pool when the **URI** number reach the limitation of the pool size. Therefore, I think maybe 
`If the service stays under load, we will in fact create a new connection for every call, which defeats the purpose of the pool` won't happen in this case.
I still think the maximum/minimum is good idea, but maybe not for the entire connection pool. Instead, it is for each entry. To be more specific, for the connection list of each entry.

Now I just evict a single connection by checking if the connection is closed or reach the maxReqCount. If using the maximum/minimum method, It would be better remove the outdated connections.

**Comment by ddobrin** [comment]
@jiachen1120 : here's the snippet which I use in a utility and I think that this is what we can incorporate. 

`			try {
				// discover the host and establish a connection if not established at start-up
				host = cluster.serviceToUrl("https", serviceID, TAG, null);
				// if discovery has failed, log the error and throw a CLientException
				if(host == null) {
					logger.error("Failed to discover service with serviceID: {}, and tag: {}", serviceID, TAG);
					throw new ClientException(String.format("Failed to discover service with serviceID: %s, and tag: %s", serviceID, TAG));
				}
				
				connection = client.connect(new URI(host), Http2Client.WORKER, Http2Client.SSL, Http2Client.BUFFER_POOL,
						OptionMap.create(UndertowOptions.ENABLE_HTTP2, useHttp2)).get();
			} catch (Exception e) {
				logger.error("Failed to connect to host: " + host, e);
				throw new ClientException(e);
			}`

**Comment by jiachen1120** [comment]
@ddobrin Thanks for sharing!!👍🏻 
yes, I agree. We should not rush for this feature. We need to make sure it is reliable and does solve our existing problems.

**Comment by chenyan71** [comment]
I am not clear about the issues. But maybe we should take a look the test cases we created on light-consumer-4j. We have concurrent service call support already on Https2Client which we create new http connection for every API call. And I don't think create new http request connection is big cost.

**Comment by stevehu** [comment]
@chenyan71 Creating a new connection per request won't have the reset issue. There are two options to create a new connection: use the same host discovered before or discover a new host. For option 1, it takes time for the handshake and establishes the connection but it is not too bad. For option 2, it resolves the re-balance issue but putting a lot of pressure on the Consul nodes or Consul agent and it would be very slow. Either HTTP/1.1 or HTTP/2 will greatly benefit from reusing an existing connection. The connection pool implementation is just a natural extension and makes the reuse easier. Of course, it increases the complexity but with proper tests, I think it is manageable.

**Comment by chenyan71** [comment]
@stevehu Agree. The connection pool will helpful for sending request multiple times to same API endpoint. So make it optional and configurable will be better option.

**Comment by ddobrin** [comment]
@jiachen1120 @chenyan71 @stevehu : 
I think configuration should allow you to decide whether you wish to re-establish a conn with the same host or re-discover.
This can be achieved also by exposing different methods.

The values for reseting (time/no of req) can be the same in both cases.

I need to use the re-connect and re-discover not just for load balancing, but to address also a Consul related issue (details left out here).

@chenyan71 : you will have the same issue when the APIs at your client site will go live 👍

**Comment by jiachen1120** [comment]
@stevehu @ddobrin Hi!
In the latest comments I have added the following improvements:
1. Provide an overloading method for callservice() to embedded service discovery and load balancing
2. Add the minConnectionNumPerHost/maxConnectionNumPerHost configuration in client.yml to control the number of connections for each host. When the number of connections exceeds 75% of the maximum number of connections, the number of connections will shrink to the minimum number of connections.
3. Add connectionExpireTime configuration in client.yml. Therefore, a connection will be evicted if: (1)connection closed (2)reach the maximum request limitation (3) expired

**Comment by stevehu** [comment]
@jiachen1120 I see that the newly added callservice will always perform service discovery. Is this method only be called when you want to reset the connection?

**Comment by jiachen1120** [comment]
@stevehu Hi! The newly added one will always perform service discovery (cached after the first time, the local cache will be notified when consul status change). Therefore, there will be a balance between each host. 

The connection will be reset for both callServices method (call service by using uri directly/ call service by using service Id) in three scenarios: (1)connection closed (2)reach the maximum request limitation (3) expired.

**Pull request merged**
