### PR TITLE
Fix cases where Connection Establishment Timed Out is incorrectly logged (1.6.x) (SimplePool)

### PR DESCRIPTION
**Pull request by miklish**
Issue: https://github.com/networknt/light-4j/issues/2172

In SimpleUndertowConnectionMaker, it is possible that a connection failure can be mis-logged as a connection timeout.

This fix corrects this and also adds more details to the logs about the cause of connection failures.

NOTE:
- _Please merge PR https://github.com/networknt/light-4j/pull/2090 before this._
  because:
- _This issue's PR contains the updated code from PR https://github.com/networknt/light-4j/pull/2090._

### CODE REVIEW

**Comment by miklish** [comment]
@stevehu hi steve - can u reopen this PR? I replaced the PR branch which seems to have caused the PR to be auto-closed. thx

**Comment by stevehu** [comment]
The Reopen button is greyed out for me. I think the underline branch is gone so we have to recreate the PR from the new replaced branch.

**Comment by miklish** [comment]
@stevehu thx. i will recreate it

**Comment by miklish** [comment]
@stevehu - fyi: recreated PR at https://github.com/networknt/light-4j/pull/2178

**Pull request closed without merging**
