### PR TITLE
Update BodyConverter.java

### PR DESCRIPTION
**Pull request by thirtysixmm**
Bug fix when using File as the FormData value.

### CODE REVIEW

**Comment by stevehu** [comment]
@thirtysixmm Thanks a lot for the enhancement. My understanding is that it is not introduced by the new version of Undertow but a missed feature in the original implementation. Please correct me if I am wrong.

**Comment by stevehu** [comment]
[Update BodyConverter.java to handle files master](https://trello.com/c/TRoIuWRS/668-update-bodyconverterjava-to-handle-files-master)

**Comment by thirtysixmm** [comment]
Thank you for accepting my PR. Not sure what changed. I used to read form data value like the below code before upgrade

```
Map<String, Object> body = (Map) exchange.getAttachment(BodyHandler.REQUEST_BODY);
ArrayList<FormData.FormValue> data = (ArrayList<FormData.FormValue>) body.get("data");
ArrayList<FormData.FormValue> files = (ArrayList<FormData.FormValue>) body.get("files");
```

After upgrading to the latest version, my handler code changed to.

```
Map<String, Object> body = (Map) exchange.getAttachment(BodyHandler.REQUEST_BODY);
String data = (String) body.get("data");
FileItem file = (FileItem) body.get("files");
```

**Comment by stevehu** [comment]
It looks like the FileItem is newly introduced in the latest version. Thanks a lot for the investigation and fix.

**Pull request merged**
