### PR TITLE
issue_1808 - Issue a non-blocking call so that the cache is refreshed without waiting for a timeout

### PR DESCRIPTION
**Pull request by zabooma**
issue #1808 and also:
Cleanup unused OptionMap initialization in ConsulClientImpl constructor and import.

### CODE REVIEW

**Comment by miklish** [comment]
Hi @zabooma -- I need to understand the additional changes in this PR.

Why are there changes to ConsulClientImpl and Http2Client?

For example, why was this removed from ConsulClientImpl?

```java
optionMap = isHttp2() ? OptionMap.create(UndertowOptions.ENABLE_HTTP2, true) : OptionMap.EMPTY;
```
?

From the PR description, the only change needed is a 1 line change in ConsulRegistry.

**Comment by miklish** [comment]
@zabooma: @AkashWorkGit informed me that the changes to ConsulClientImpl were supposed to be in https://github.com/networknt/light-4j/pull/1821

**Comment by zabooma** [comment]
@miklish : optionMap was identified as not used after all the changes we have made recently (switching to a different connection pool use). On one of the calls you asked to remove it on any of the outstanding PRs.

**Comment by AkashWorkGit** [comment]
The Junit could not be created for the changes in consulCientImpl class after several attempts but the manual unit test & functional testing was completed successfully.

**Review by jaydeepparekh1311 — APPROVED** [review]

**Review by miklish — APPROVED** [review]

**Pull request merged**
