### PR TITLE
Issue1055

### PR DESCRIPTION
**Pull request by jaydeepparekh1311**
Updates incorporated based on review comments

### CODE REVIEW

**Comment by jaydeepparekh1311** [comment]
Updates incorporated based on review comments

**Review by miklish — APPROVED** [review]

**Comment by miklish** [comment]
Thanks for the update @jaydeepparekh1311 ... I have approved this now

**Review by stevehu — APPROVED** [review]

**Comment by stevehu** [comment]
@jaydeepparekh1311 @miklish Do you have further changes to the 1.6.x branch? if not, I will start the release process. Thanks.

**Comment by miklish** [comment]
No, we're good Steve... please proceed. Thanks

**Pull request merged**
