### PR TITLE
Update SingletonServiceFactory.java

### PR DESCRIPTION
**Pull request by ruslanys**
Please, make getBean(...) method more convenience

### CODE REVIEW

**Comment by stevehu** [comment]
Nice. I got it done and never looked back :) Thanks a lot for your help.

**Comment by stevehu** [comment]
In light-eventuate-4j framework, one interface has multiple implementations and it returns object array. 

```
                (EventHandlerProcessor[])SingletonServiceFactory.getBean(EventHandlerProcessor.class),

```

**Comment by ruslanys** [comment]
All right. I'll make pull request. Where else?

**Comment by stevehu** [comment]
I think that is the only place that is broken. I rollback just to get a quick release out as one of our customers is waiting.

**Comment by ruslanys** [comment]
@stevehu No problem! I'm glad to help :wink:

**Pull request merged**
