### PR TITLE
Fix audit issue #935 and #936

### PR DESCRIPTION
**Pull request by jsu216**
Fix the two issues #935 and #936

### CODE REVIEW

**Comment by miklish** [comment]
FYI: We are waiting for our client to review and test these changes before submit any approvals

**Comment by chenyan71** [comment]
I add some concerns below for this PR, not sure if it is valid:

1. why auditRequest need statusCode and responseTime to be true in the config? (it moved into if block):
          if (auditConfig.isStatusCode() || auditConfig.isResponseTime()) {
            exchange.addExchangeCompleteListener((exchange1, nextListener) -> {
                auditRequest(**exchange**, auditMap, auditConfig);
    Should it be:   auditRequest(**exchange1**, auditMap, auditConfig); ?

2. for the requestBody method change, it make sense to log the  json （application/json） to audit log as issue m#935 mentioned.
    But if the json convert failed by Objectmapper with exception：

                try {
                    requestBodyString = Config.getInstance().getMapper().writeValueAsString(requestBody);
                } catch (JsonProcessingException e) {
                    logger.error("Failed to audit log request body", e);
                }

   The requestBodyString  will be still  null and handler will skip next if statement (if (requestBodyString != null)) . So the audit log will still not have invalid json string for user to audit(I am not sure if it is PR requestor wanted). So I suggest we integrate two if statements together. When exception happen, add the raw string to audit log.

3. for the binary format requestbody (InputStream for pdf, image, ...), do we need add it to audit log? It may mess the audit log.
  content-type not in ("application/json", "text/plain", "multipart/form-data", "application/x-www-form-urlencoded")

**Comment by jsu216** [comment]
Thanks @chenyan71 for your comment. My replies are below and I will make some changes to the PR accordingly.

> I add some concerns below for this PR, not sure if it is valid:
> 
> 1. why auditRequest need statusCode and responseTime to be true in the config? (it moved into if block):
>    if (auditConfig.isStatusCode() || auditConfig.isResponseTime()) {
>    exchange.addExchangeCompleteListener((exchange1, nextListener) -> {
>    auditRequest(**exchange**, auditMap, auditConfig);
>    //Should it be:   auditRequest(**exchange1**, auditMap, auditConfig); ?

This PR does not change condition when the "addExchangeCompleteListener" is set, but only moves the "auditRequest" and others into the listener. I agree that this changes the condition that these audit functions being called. I will move the status and responsetime  check into the listener as well.

> 2. for the requestBody method change, it make sense to log the  json （application/json） to audit log as issue m#935 mentioned.
>    But if the json convert failed by Objectmapper with exception：
>    ```
>             try {
>                 requestBodyString = Config.getInstance().getMapper().writeValueAsString(requestBody);
>             } catch (JsonProcessingException e) {
>                 logger.error("Failed to audit log request body", e);
>             }
>    ```
>    
>    
>    The requestBodyString  will be still  null and handler will skip next if statement (if (requestBodyString != null)) . So the audit log will still not have invalid json string for user to audit(I am not sure if it is PR requestor wanted). So I suggest we integrate two if statements together. When exception happen, add the raw string to audit log.

This only happens when the REQUEST_BODY attachment is populated as an object but cannot be serialized as a Json String.
I will make the change to use Object.toString() as the requestBodyString to avoid missing it in audit log.

> 3. for the binary format requestbody (InputStream for pdf, image, ...), do we need add it to audit log? It may mess the audit log.
>    content-type not in ("application/json", "text/plain", "multipart/form-data", "application/x-www-form-urlencoded")

This is not in the scope of this PR. We need another issue or feature to address this.

**Comment by chenyan71** [comment]
@jsu216  Thanks for the update. Please ignore the item 3.
I will create a separate issue for it and ask @stevehu  to verify.

**Review by zabooma — APPROVED** [review]

**Review by stevehu — APPROVED** [review]

**Pull request merged**
