### PR TITLE
Issue1304 - Add more debug and info messages

### PR DESCRIPTION
**Pull request by jsu216**

### CODE REVIEW

**Review by stevehu — APPROVED** [review]

**Comment by miklish** [comment]
@stevehu FYI: I will discuss these changes with John briefly tomorrow and then add my approval afterwards

**Comment by jsu216** [comment]
@stevehu , I added more logs for Http2Client and connection pool. Please review them. Thanks.

**Review by stevehu — APPROVED** [review]

**Comment by jsu216** [comment]
Sorry @stevehu , I made another [change](https://github.com/networknt/light-4j/pull/1309/commits/c3b9952507a8feb1d9a1a2f13a54900ad128e449) after review the PR in our team.

**Comment by stevehu** [comment]
A snapshot version 1.6.40-SNAPSHOT is released.

**Comment by miklish** [comment]
Thanks steve!

**Pull request merged**
